slsdetectorgroup/aare

CMakeLists.txt
core/CMakeLists.txt
core/include/aare/Frame.hpp
core/src/Frame.cpp
core/test/Frame.test.cpp
file_io/src/NumpyFile.cpp
file_io/src/RawFile.cpp
tests/CMakeLists.txt

- ctest now working
- renamed _get_data() to just data() (similar to vector and string)
- The data of frame is now zero initialized to avoid accessing uninitialized memory

Added tests to Frame and some cleanup

---

CMakeLists.txt
core/CMakeLists.txt
core/include/aare/ZmqSocket.hpp
core/src/ZmqSocket.cpp
etc/virtual_jf.config
examples/CMakeLists.txt
examples/zmq_example.cpp

Prototype implementation with some open questions.
- Added libzmq to the cmake file
- ZmqSocket class to receive data from slsReceiver over zmq pub/sub
**Questions**
- Should the name stay ZmqSocket? or be more specific ZmqRcvSocket? other ideas? 
- How do we pass data to the socket? Size of frame passed? 
- Tests how to decode the zmqHeader?

ZmqSocket prototype

---

file_io/include/aare/file_io/FileInterface.hpp
file_io/include/aare/file_io/RawFile.hpp

make file interface and rawfile variables private

---

COPYING
LICENSES/GPL-3.0
LICENSES/LGPL-3.0
LICENSES/Third Party/Apache-2.0
etc/config

add license2

---

src/core/CMakeLists.txt
src/processing/include/aare/processing/Pedestal.hpp
src/processing/src/Pedestal.cpp
src/processing/test/pedestal.test.cpp
tests/test.cpp

template the type of m_sum and m_sum2 in pedestal

template pedestal

---

examples/CMakeLists.txt
examples/clustering.cpp
src/core/include/aare/core/MultiThread.hpp
src/core/include/aare/core/ProducerConsumerQueue.hpp
src/python/cpp/core.hpp
src/python/cpp/file_io.hpp
src/python/cpp/processing.hpp
src/python/example/mt_clusterFinder.py

- Small modifications to the ProducerConsumerQueue to allow for storage in a vector
- Example showing multi threading in C++ using queues
- fixes for python bindings

Cpp multi example

---

CMakeLists.txt
benchmarks/CMakeLists.txt
benchmarks/ndarray_benchmark.cpp
include/aare/ArrayExpr.hpp
include/aare/NDArray.hpp
include/aare/NDView.hpp
python/examples/play.py
src/NDArray.test.cpp
src/NumpyFile.test.cpp
src/RawFile.test.cpp
src/RawMasterFile.test.cpp
tests/test.cpp

- Works with NDArray
- Works with NDView

Added expression templates

---

CMakeLists.txt
python/CMakeLists.txt

- added AARE_INSTALL_PYTHONEXT option to install also python files in aare folder

AARE_INSTALL_PYTHONEXT

---

include/aare/defs.hpp
src/defs.cpp
src/defs.test.cpp

- Missing enums
- Matching values to slsDetectorPackage
- tests

added missing enums

---

conda-recipe/meta.yaml
include/aare/CircularFifo.hpp
include/aare/ClusterCollector.hpp
include/aare/ClusterFile.hpp
include/aare/ClusterFileSink.hpp
include/aare/ClusterFinder.hpp
include/aare/ClusterFinderMT.hpp
include/aare/ClusterVector.hpp
include/aare/File.hpp
include/aare/ProducerConsumerQueue.hpp
pyproject.toml
python/aare/__init__.py
python/examples/play.py
python/src/cluster.hpp
python/src/cluster_file.hpp
python/src/file.hpp
python/src/module.cpp
src/ClusterFile.cpp
src/File.cpp

Added a prototype for the multi threaded cluster finder including python bindings

Multi threaded cluster finder.

---

CMakeLists.txt
include/aare/RawFile.hpp
include/aare/RawMasterFile.hpp
include/aare/defs.hpp
include/aare/geo_helpers.hpp
python/examples/play.py
src/RawFile.cpp
src/RawFile.test.cpp
src/RawSubFile.cpp
src/geo_helpers.cpp
src/geo_helpers.test.cpp

- Bugfixes
- New abstraction for detector geometry
- Tests for updating geo with ROI

Fixing ROI read of RawFile

---

CMakeLists.txt
include/aare/Fit.hpp
include/aare/NDArray.hpp
include/aare/NDView.hpp
include/aare/utils/par.hpp
python/CMakeLists.txt
python/examples/play.py
python/src/fit.hpp
src/Fit.cpp
src/NDArray.test.cpp

- fit_gaus and fit_pol1 now return a dict
- calculate chi2 after fit
- cleaned up code

Added chi2 to fit results

---

src/ClusterFile.cpp

Fixed incorrect reading of clusters with ROI
closes #141

Fixed reading clusters with ROI

---

python/aare/__init__.py
python/src/cluster.hpp
python/src/module.cpp

This example now works:
```python
cl = Cluster3x3i(5,7,np.array((1,2,3,4,5,6,7,8,9), dtype = np.int32))
cv = ClusterVector_Cluster3x3i()
cv.push_back(cl)
```

function signature for push back

---

CMakeLists.txt
docs/src/JungfrauDataFile.rst
docs/src/Tests.rst
docs/src/algorithm.rst
docs/src/index.rst
docs/src/pyJungfrauDataFile.rst
include/aare/FilePtr.hpp
include/aare/JungfrauDataFile.hpp
include/aare/algorithm.hpp
pyproject.toml
python/aare/__init__.py
python/src/jungfrau_data_file.hpp
python/src/module.cpp
python/tests/conftest.py
python/tests/test_jungfrau_dat_files.py
src/ClusterFile.test.cpp
src/File.cpp
src/FilePtr.cpp
src/JungfrauDataFile.cpp
src/JungfrauDataFile.test.cpp
src/algorithm.test.cpp

closes #150 
**Not addressed in this PR:** 
- pixels_per_frame, bytes_per_frame and tell should be made cost in FileInterface

Adding support for Jungfrau .dat files

---

include/aare/JungfrauDataFile.hpp
include/aare/NDArray.hpp
include/aare/NDView.hpp
include/aare/VarClusterFinder.hpp
src/Fit.cpp
src/Interpolator.cpp
src/JungfrauDataFile.cpp
src/JungfrauDataFile.test.cpp
src/NDArray.test.cpp
src/algorithm.test.cpp

Fixed warnings:
- unused variable in Interpolator
- Narrowing conversions uint64-->int64
Removed an ambiguous function from JungfrauDataFile
- NDarry read_frame(header&=nullptr)
- Frame read_frame()

fixed warnings and removed ambiguous read_frame

---

CMakeLists.txt
include/aare/RawSubFile.hpp
include/aare/utils/ifstream_helpers.hpp
python/src/file.hpp
python/src/module.cpp
python/src/raw_sub_file.hpp
python/tests/test_RawSubFile.py
src/RawSubFile.cpp
src/utils/ifstream_helpers.cpp

- Removed a printout left from debugging
- return also header when reading
- added read_n 
- check for error in ifstream

Making RawSubFile usable from Python

---

.github/workflows/build_wheel.yml
.gitignore
CMakeLists.txt
pyproject.toml
python/CMakeLists.txt

Still to be resolved in another PR: 
- Consistent versioning across compiled code, conda and pypi

Building wheels and uploading to pypi

---

CMakeLists.txt
src/JungfrauDataFile.cpp
src/NumpyFile.cpp
src/RawFile.cpp
src/RawMasterFile.cpp

- Fixing broken build of tests on RH8 by linking pthreads
- Removed extra ; causing warnings with -Wpedantic

linking to threads and removed extra ;

---

include/aare/NDView.hpp
src/NDView.test.cpp

- Added const element access
- Added const data*
- Fixed bug comparing two Views of same size but different shapes
closes #207

Const element access and fixed comparing bug

---

include/aare/NDArray.hpp
include/aare/NDView.hpp
include/aare/calibration.hpp
src/NDArray.test.cpp

- helper function to initialize shape
- helper function to calculate the number of elements
- move constructor to create a NDArray<T, Ndim-1> if sizes match

Move constructor to drop 1st dimension of NDArray

---

benchmarks/CMakeLists.txt
benchmarks/reduce_benchmark.cpp
docs/src/ClusterVector.rst
docs/src/pyClusterVector.rst
include/aare/CalculateEta.hpp
include/aare/Cluster.hpp
include/aare/ClusterVector.hpp
python/aare/__init__.py
python/src/bind_Cluster.hpp
python/src/bind_ClusterVector.hpp
python/src/module.cpp
python/tests/test_Cluster.py
python/tests/test_ClusterVector.py
src/Cluster.test.cpp

Generalized reduction to 3x3 and 3x3 clusters for general sized clusters.

General reduce
